# Generated by Django 4.2.6 on 2023-11-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_rename_bids_bid_alter_auction_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="img",
            field=models.URLField(null=True),
        ),
    ]
