# Generated by Django 4.2.6 on 2023-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_auction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
